name: tflint
description: tflint action
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  working_directory:
    description: 'Working Directory'
    required: false
    default: ""
runs:
  using: node16
  main: dist/index.js
