---
name: Create Pull Request Branch
run-name: Create Pull Request Branch (${{inputs.pr}})
on:
  workflow_dispatch:
    inputs:
      pr:
        type: number
        description: "Pull Request Number"
        required: true
      is_comment:
        description: Whether a comment is posted
        type: boolean
        required: true
jobs:
  create-pr-branch:
    uses: ./.github/workflows/workflow_call_release.yaml
    permissions:
      contents: write
      pull-requests: write
    with:
      version: pr/${{inputs.pr}}
      pr: ${{inputs.pr}}
      is_comment: ${{inputs.is_comment}}
