name: Update the latest branch
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/workflow_call_release.yaml
    permissions:
      contents: write
      pull-requests: write
    with:
      version: latest
