name: test (workflow_call)
on: workflow_call
permissions: {}
jobs:
  path-filter:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    outputs:
      renovate-config-validator: ${{steps.changes.outputs.renovate-config-validator}}
    permissions: {}
    steps:
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            renovate-config-validator:
              - renovate.json
              - .github/workflows/test.yaml
              - .github/workflows/workflow_call_renovate-config-validator.yaml
  # test:
  #   uses: ./.github/workflows/workflow_call_test_action.yaml
  #   permissions:
  #     pull-requests: write # For reviewdog

  renovate-config-validator:
    uses: ./.github/workflows/workflow_call_renovate-config-validator.yaml
    needs: path-filter
    if: needs.path-filter.outputs.renovate-config-validator == 'true'
    permissions:
      contents: read

  create-pr-branch:
    uses: ./.github/workflows/workflow_call_release.yaml
    if: github.event.pull_request.user.login == 'suzuki-shunsuke'
    permissions:
      contents: write
      pull-requests: write
    with:
      version: pr/${{github.event.pull_request.number}}
      pr: ${{github.event.pull_request.number}}
